import Notifications from './Notifications'
import {usePageMotion} from '../hooks/usePageMotion'
import {useState,useEffect,useRef} from 'react'
import {gsap} from 'gsap'
import {NavLink,Outlet,Navigate,useNavigate,useLocation,Link} from 'react-router-dom'
import {LayoutDashboard,Upload,History,BookOpen,Layers,Sparkles,LogOut,Menu,X,Archive} from './Icons'
import {TrendingUp,Gem,MessageCircleHeart,PanelLeftClose,PanelLeftOpen,UserPlus,LogIn,ChevronsUpDown} from 'lucide-react'
import {PlanBadge} from './Premium'
import TutorWidget from './TutorWidget'
import BillingButton from './BillingButton'
import DemoLock from './DemoLock'
import {TEST} from '../services/api'
import {useScrollReveal} from '../hooks/useScrollReveal'
import {useApp} from '../context/AppContext'
import {Brand,Language,Busy,ErrorBox} from './UI'
export default function Layout(){
 const {tr,user,loading,logout,settings,loadError,refresh,storageError}=useApp(),nav=useNavigate(),location=useLocation()
 useScrollReveal(location.pathname)
 const[collapsed,setCollapsed]=useState(()=>{try{return localStorage.getItem('adapted-sidebar-collapsed')==='1'}catch{return false}})
 const[menu,setMenu]=useState(false),menuRef=useRef(null)
 function toggleSidebar(){const next=!collapsed;setCollapsed(next);try{localStorage.setItem('adapted-sidebar-collapsed',next?'1':'0')}catch{            }
  const mark=document.querySelector('.sidebar .brand-symbol');if(mark&&!window.matchMedia?.('(prefers-reduced-motion: reduce)').matches)gsap.fromTo(mark,{rotationY:0,scale:1},{rotationY:360,scale:1.12,duration:.7,ease:'power3.inOut',yoyo:false,onComplete:()=>gsap.set(mark,{scale:1,rotationY:0})})}
 useEffect(()=>{if(!menu)return;const close=e=>{if(e.type==='keydown'?e.key==='Escape':!menuRef.current?.contains(e.target))setMenu(false)};document.addEventListener('mousedown',close);document.addEventListener('keydown',close);return()=>{document.removeEventListener('mousedown',close);document.removeEventListener('keydown',close)}},[menu])
 usePageMotion(location.pathname)
 const[open,setOpen]=useState(false),[error,setError]=useState('')
 if(loading)return <Busy>{tr('Loading your workspace…','جارٍ فتح مساحة العمل…')}</Busy>
 if(!user)return <Navigate to="/login" replace state={{from:location.pathname}}/>
 
 
 if(user.role==='student'&&!location.pathname.startsWith('/app/student'))return <Navigate to="/app/student" replace/>
 if(user.role!=='student'&&location.pathname.startsWith('/app/student'))return <Navigate to="/app" replace/>
 const items=user.role==='student'?[['/app/student',LayoutDashboard,tr('My lessons','دروسي')],['/app/student/upload',Upload,tr('Upload lesson','رفع درس')],['/app/student/tools/generate',Sparkles,tr('Generate','التوليد')],['/app/student/tools/quiz',BookOpen,tr('Quiz','الاختبارات')],['/app/student/tools/flashcards',Layers,tr('Flashcards','بطاقات المراجعة')],['/app/student/progress',TrendingUp,tr('My progress','تقدّمي')],['/app/student/tutor',MessageCircleHeart,tr('Study Tutor','مساعد التعلّم')],['/app/student/archive',Archive,tr('Archive','الأرشيف')]]:[['/app',LayoutDashboard,tr('Overview','نظرة عامة')],['/app/upload',Upload,tr('New lesson','درس جديد')],['/app/history',History,tr('Lesson library','مكتبة الدروس')],['/app/archive',Archive,tr('Archive','الأرشيف')],['/app/tutor',MessageCircleHeart,tr('Teaching Assistant','مساعد المعلم')],['/app/plans',Gem,tr('Plans','الخطط')]]
 return <div style={{'--reading-scale':settings.scale||1}} className={`workspace ${user.role==='student'?'is-student-workspace':''} ${collapsed?'sidebar-collapsed':''} ${settings.large?'large-type':''} ${settings.contrast?'high-contrast':''}  ${settings.comfort?'reading-comfort':''} reading-scale`}>
 <a className="skip" href="#workspace-main">{tr('Skip to content','انتقل إلى المحتوى')}</a><aside className={`sidebar ${open?'is-open':''}`}><div className="sidebar-brand"><Brand/><button className="icon-btn sidebar-toggle" aria-label={collapsed?tr('Expand menu','توسيع القائمة'):tr('Collapse menu','طي القائمة')} title={collapsed?tr('Expand menu','توسيع القائمة'):tr('Collapse menu','طي القائمة')} aria-pressed={collapsed} onClick={toggleSidebar}>{collapsed?<PanelLeftOpen size={18}/>:<PanelLeftClose size={18}/>}</button><button className="icon-btn mobile-only" aria-label={tr('Close menu','إغلاق القائمة')} onClick={()=>setOpen(false)}><X/></button></div><p className="nav-label">{tr('YOUR WORKSPACE','مساحة عملك')}</p><nav className="side-nav">{items.map(([to,Icon,label])=><NavLink end={to==='/app'||to==='/app/student'} key={to} to={to} data-label={label} aria-label={label} onClick={()=>setOpen(false)}><Icon size={19}/><span className="nav-text">{label}</span></NavLink>)}</nav><div className="sidebar-bottom"><span className="avatar">{user.name?.slice(0,1)||'A'}</span><div><strong>{user.name}</strong><small>{user.role==='student'?tr('Student','طالب'):tr('Teacher','معلم')} <PlanBadge compact/></small></div><div className="account-menu" ref={menuRef}><button className="icon-btn" aria-haspopup="menu" aria-expanded={menu} aria-label={tr('Account options','خيارات الحساب')} onClick={()=>setMenu(v=>!v)}><ChevronsUpDown size={17}/></button>{menu&&<div className="account-pop" role="menu"><button role="menuitem" onClick={()=>{setMenu(false);nav('/login',{state:{from:'/app'}})}}><LogIn size={16}/>{tr('Add another account','إضافة حساب آخر')}</button><button role="menuitem" onClick={()=>{setMenu(false);nav('/register',{state:{from:'/app'}})}}><UserPlus size={16}/>{tr('Create a new account','إنشاء حساب جديد')}</button><hr/><button role="menuitem" className="is-danger" onClick={async()=>{setMenu(false);try{await logout();nav('/')}catch{setError(tr('Could not log out. Try again.','تعذّر تسجيل الخروج. حاول مجدداً.'))}}}><LogOut size={16}/>{tr('Log out','تسجيل الخروج')}</button></div>}</div></div></aside>
 {open&&<button className="sidebar-scrim" aria-label={tr('Close menu','إغلاق القائمة')} onClick={()=>setOpen(false)}/>}
 
 
 <div className="workspace-body"><div className="workspace-top"><button className="icon-btn mobile-only" aria-label={tr('Open menu','فتح القائمة')} onClick={()=>setOpen(true)}><Menu/></button><span className="breadcrumb">AdaptEd <span>/</span> {location.pathname.includes('/upload')?tr('New lesson','درس جديد'):location.pathname.includes('/student/progress')?tr('My progress','تقدّمي'):location.pathname.includes('/student/tutor')?tr('Study Tutor','مساعد التعلّم'):location.pathname.includes('/tutor')?tr('Teaching Assistant','مساعد المعلم'):location.pathname.includes('/upgrade')?tr('Upgrade','الترقية'):location.pathname.includes('/plans')?tr('Plans','الخطط'):location.pathname.includes('/checkout')?tr('Checkout','إتمام الاشتراك'):location.pathname.includes('/student/archive')?tr('Archive','الأرشيف'):location.pathname.includes('/student/library')?tr('Lesson library','مكتبة الدروس'):location.pathname.includes('/student/result')?tr('Lesson studio','استوديو الدرس'):location.pathname.includes('/student')?tr('My lessons','دروسي'):location.pathname.includes('/archive')?tr('Archive','الأرشيف'):location.pathname.includes('/history')?tr('Lesson library','مكتبة الدروس'):location.pathname.includes('/result/')?tr('Lesson studio','مساحة الدرس'):tr('Overview','نظرة عامة')}</span><div className="top-tools">{user.demo&&(TEST?<span className="demo-pill"><span aria-hidden="true"/>{tr('Local test · sample results','اختبار محلي · نتائج نموذجية')}</span>:<button type="button" className="demo-pill" onClick={()=>window.dispatchEvent(new CustomEvent('adapted:demo-lock'))}><span aria-hidden="true"/>{tr('Demo · browse only','تجريبي · للتصفح فقط')}</button>)}{user.role!=='student'&&<><PlanBadge compact/><BillingButton/></>}<Notifications/><Language/></div></div>

 
 <main className="page-content" id="workspace-main">{TEST&&<p className="test-mode-banner">{tr('Local test mode: features use sample content and browser storage. Your files are not sent to the server.','وضع اختبار محلي: الميزات تستخدم محتوى نموذجياً وتخزين المتصفح. ملفاتك لا تُرسل للخادم.')}</p>}<ErrorBox>{error}</ErrorBox>{storageError&&<ErrorBox>{tr('Browser storage is unavailable. Changes may be lost after closing this page.','التخزين المحلي غير متاح. قد تفقد التغييرات بعد إغلاق الصفحة.')}</ErrorBox>}{loadError&&<div className="error-box">{tr('Could not load lessons.','تعذّر تحميل الدروس.')} <button onClick={refresh}>{tr('Retry','إعادة المحاولة')}</button></div>}<Outlet/></main><TutorWidget/>{!TEST&&<DemoLock/>}<div className="workspace-footer">AdaptEd <span>·</span> {tr('Your expertise. More possibilities.','خبرتك التعليمية. إمكانات أوسع.')} <span>·</span> <Link to="/contact">{tr('Contact us','تواصل معنا')}</Link></div></div></div>
}
