import {useState} from 'react'
import {ArrowRight,Check,BookOpen,Sparkles} from 'lucide-react'
import {useApp} from '../context/AppContext'
const copy={
 en:{label:'SEE THE DIFFERENCE',title:'Same idea. A clearer way in.',intro:'Explore one short example. Choose the support and see how the lesson changes.',sample:'Illustrative example · Teacher-reviewed before use',original:'Original lesson',adapted:'Adapted lesson',modes:['Focused steps','Simpler reading'],text:'Evaporation occurs when liquid water absorbs sufficient thermal energy to transition into a gaseous state. Water vapor subsequently cools and condenses into droplets, forming clouds, before returning to the surface as precipitation.',steps:['The sun warms the water.','Some water turns into vapor and rises.','The vapor cools into tiny drops that form clouds.','Water falls back to Earth as rain or snow.'],simple:'The sun heats water. Some water becomes a gas called water vapor. The vapor rises and cools. It turns into tiny drops that form clouds. The water returns as rain or snow.',question:'What helps water turn into vapor?',answers:['Heat from the sun','Cold air'],right:'Yes. Heat helps liquid water become vapor.',wrong:'Think about what warms the water. Try again.',note:'Shorter steps. One idea at a time.',readNote:'Familiar words. The meaning stays.'},
 ar:{label:'شاهد الفرق',title:'الفكرة نفسها. طريق أوضح للفهم.',intro:'جرّب مثالاً قصيراً. اختر نوع الدعم وشاهد كيف يتغيّر عرض الدرس.',sample:'مثال توضيحي · يراجعه المعلم قبل الاستخدام',original:'الدرس الأصلي',adapted:'الدرس المكيّف',modes:['خطوات للتركيز','قراءة أبسط'],text:'يحدث التبخّر عندما يمتص الماء السائل طاقة حرارية كافية للانتقال إلى الحالة الغازية. ثم يبرد بخار الماء ويتكاثف إلى قطرات تكوّن السحب، قبل أن يعود إلى سطح الأرض على شكل هطول.',steps:['تسخّن الشمس الماء.','يتحوّل بعض الماء إلى بخار ويرتفع.','يبرد البخار ويتحوّل إلى قطرات صغيرة تكوّن السحب.','يعود الماء إلى الأرض مطراً أو ثلجاً.'],simple:'تسخّن الشمس الماء. يتحوّل بعضه إلى غاز اسمه بخار الماء. يرتفع البخار ويبرد، ثم يتحوّل إلى قطرات صغيرة تكوّن السحب. يعود الماء إلى الأرض مطراً أو ثلجاً.',question:'ما الذي يساعد الماء على التحوّل إلى بخار؟',answers:['حرارة الشمس','الهواء البارد'],right:'صحيح. تساعد الحرارة الماء السائل على التحوّل إلى بخار.',wrong:'فكّر بما يسخّن الماء، وحاول مرة أخرى.',note:'خطوات قصيرة. فكرة واحدة في كل مرة.',readNote:'كلمات مألوفة. المعنى يبقى.'},
 ckb:{label:'جیاوازییەکە ببینە',title:'هەمان بیرۆکە. ڕێگایەکی ڕوونتر بۆ تێگەیشتن.',intro:'نموونەیەکی کورت تاقی بکەرەوە. پشتگیری هەڵبژێرە و گۆڕانی وانەکە ببینە.',sample:'نموونەی ڕوونکردنەوە · پێش بەکارهێنان مامۆستا پێداچوونەوەی بۆ دەکات',original:'وانەی سەرەکی',adapted:'وانەی گونجاو',modes:['هەنگاو بۆ سەرنجدان','خوێندنەوەی ئاسانتر'],text:'هەڵمبوون کاتێک ڕوودەدات کە ئاوی شل گەرمیی پێویست وەردەگرێت و دەبێتە گاز. هەڵمی ئاو پاشان سارد دەبێتەوە و دەبێتە دڵۆپ و هەور دروست دەکات، پێش ئەوەی بە شێوەی باران یان بەفر بگەڕێتەوە بۆ زەوی.',steps:['خۆر ئاو گەرم دەکات.','بەشێک لە ئاو دەبێتە هەڵم و بەرز دەبێتەوە.','هەڵم سارد دەبێتەوە و دەبێتە دڵۆپی بچووک کە هەور دروست دەکات.','ئاو بە باران یان بەفر دەگەڕێتەوە بۆ زەوی.'],simple:'خۆر ئاو گەرم دەکات. بەشێکی دەبێتە هەڵمی ئاو. هەڵم بەرز دەبێتەوە و سارد دەبێتەوە. دەبێتە دڵۆپی بچووک و هەور دروست دەکات. ئاو بە باران یان بەفر دەگەڕێتەوە.',question:'چی یارمەتی ئاو دەدات ببێتە هەڵم؟',answers:['گەرمیی خۆر','هەوای سارد'],right:'ڕاستە. گەرمی یارمەتی ئاو دەدات ببێتە هەڵم.',wrong:'بیر بکەرەوە چی ئاو گەرم دەکات. دووبارە هەوڵ بدەرەوە.',note:'هەنگاوی کورت. هەر جارە بیرۆکەیەک.',readNote:'وشەی ئاشنا. واتاکە دەمێنێتەوە.'}
}
export default function LessonComparison(){const{lang}=useApp(),t=copy[lang]||copy.en,[mode,setMode]=useState(0),[answer,setAnswer]=useState(null)
 return <section className="lesson-comparison" aria-labelledby="comparison-title"><div className="comparison-heading"><div><p className="eyebrow">{t.label}</p><h2 id="comparison-title">{t.title}</h2><p>{t.intro}</p></div><div className="comparison-switch" role="group" aria-label={t.adapted}>{t.modes.map((label,i)=><button key={label} aria-pressed={mode===i} onClick={()=>{setMode(i);setAnswer(null)}}>{label}</button>)}</div></div><div className="comparison-panels"><article className="before-panel"><span className="comparison-label"><BookOpen size={17}/>{t.original}</span><p>{t.text}</p><span className="comparison-arrow" aria-hidden="true"><ArrowRight size={21}/></span></article><article className="after-panel"><span className="comparison-label"><Sparkles size={17}/>{t.adapted}</span><div key={mode} className="adapted-example">{mode===0?<ol>{t.steps.map((step,i)=><li key={i}><span>{String(i+1).padStart(2,'0')}</span>{step}</li>)}</ol>:<p>{t.simple}</p>}<div className="comparison-takeaway"><Check size={16}/>{mode===0?t.note:t.readNote}</div></div></article></div><div className="example-check"><strong>{t.question}</strong><div>{t.answers.map((label,i)=><button key={label} aria-pressed={answer===i} onClick={()=>setAnswer(i)}>{label}</button>)}</div>{answer!==null&&<p role="status" className={answer===0?'is-correct':''}>{answer===0?t.right:t.wrong}</p>}</div><p className="comparison-disclaimer">{t.sample}</p></section>
}
