import {useRef} from 'react'
import {Link,useNavigate} from 'react-router-dom'
import {LiveClassCreate} from '../components/LiveClassCard'
import {useHeroMotion} from '../hooks/useHeroMotion'
/* Wrap each word so the headline can rise in word by word. */
const words=text=>String(text).split(' ').flatMap((w,i,a)=>[<span className="hw" key={i}><span>{w}</span></span>,i<a.length-1?' ':null])
import {ArrowUpRight,Plus,FileText,Sparkles,BookOpen,Layers,ArrowRight,Check,Upload} from '../components/Icons'
import {useApp} from '../context/AppContext'
import {PageHeading,LessonRow,Empty} from '../components/UI'
import {makeSample} from '../data/demo'
import {DEMO} from '../services/api'
import {CountUp} from '../components/Motion'
import QuickAsk from '../components/QuickAsk'
export default function Dashboard(){
 const{tr,lang,user,lessons,addLesson}=useApp(),navigate=useNavigate(),heroRef=useRef(null)
 const hour=new Date().getHours(),first=(user?.name||'').split(' ')[0]
 const greeting=`${hour<12?tr('Good morning','صباح الخير'):hour<18?tr('Good afternoon','نهارك سعيد'):tr('Good evening','مساء الخير')}${first?`, ${first}`:''}.`
 useHeroMotion(heroRef,lang)
 const versions=lessons.reduce((n,l)=>n+Object.keys(l.outputs).length,0),drafts=lessons.filter(l=>!Object.keys(l.outputs).length).length
 function sample(){const lesson=makeSample(lang);addLesson(lesson);navigate(`/app/result/${lesson.id}`)}
 const steps=[[Upload,tr('Bring your lesson','أحضر درسك'),tr('Start with a PDF you already teach.','ابدأ بملف PDF من دروسك.')],[Sparkles,tr('Shape the support','اختر الدعم المناسب'),tr('Choose the format and learning needs.','حدّد شكل المحتوى واحتياجات التعلّم.')],[BookOpen,tr('Make it theirs','شاركه مع طلابك'),tr('Review, refine, and share with students.','راجع المحتوى وعدّله وشاركه مع الطلاب.')]]
 return <><PageHeading eyebrow={tr('YOUR TEACHING, REIMAGINED','تعليمك بإمكانات أوسع')} title={greeting} description={`${tr('Welcome back,','أهلاً بعودتك،')} ${user.name}.`}><Link to="/app/upload" className="primary-btn"><Plus size={18}/>{tr('New lesson','درس جديد')}</Link></PageHeading>
 <section className="editorial-hero" ref={heroRef}><div className="hero-aurora" aria-hidden="true"><i/><i/><i/></div><div className="hero-sparks" aria-hidden="true">{Array.from({length:14},(_,i)=><i key={i}/>)}</div><div className="editorial-copy"><span className="hero-overline"><span/> {tr('ONE LESSON. EVERY LEARNER.','درس واحد. لكل متعلّم.')}</span><h2 aria-label={`${tr('Less preparation.','تحضير أقل.')} ${tr('More connection.','تواصل أكبر.')}`}><span aria-hidden="true">{words(tr('Less preparation.','تحضير أقل.'))}</span><br/><em aria-hidden="true">{words(tr('More connection.','تواصل أكبر.'))}</em></h2><p>{tr('Bring your knowledge. We’ll help you make it clearer, kinder, and easier to learn.','أحضر معرفتك. نساعدك على تقديمها بوضوح وبطريقة أقرب لكل متعلّم.')}</p><Link to="/app/upload" className="hero-action"><i className="hero-shine" aria-hidden="true"/>{tr('Adapt a lesson','كيّف درساً')}<span><ArrowUpRight size={20}/></span></Link><span className="hero-footnote">{tr('Your expertise. More possibilities.','خبرتك التعليمية. إمكانات أوسع.')}</span></div>
 <div className="lesson-sculpture" aria-hidden="true"><svg className="sculpture-rings" viewBox="0 0 500 410" fill="none"><ellipse cx="250" cy="205" rx="211" ry="136" transform="rotate(-32 250 205)" stroke="#bedc7a" strokeWidth="1"/><ellipse cx="250" cy="205" rx="215" ry="138" transform="rotate(35 250 205)" stroke="#bedc7a" strokeWidth="1"/><circle cx="416" cy="118" r="7" fill="#d9efa3"/><circle cx="88" cy="270" r="4" fill="#d9efa3"/><circle className="orbit-dot" cx="0" cy="0" r="5" fill="#e9ffc0"/><circle className="orbit-dot" cx="0" cy="0" r="3.5" fill="#c6ec34"/></svg><div className="sculpture-paper sculpture-paper-back"/><div className="sculpture-paper"><div className="sculpture-paper-top"><span><FileText size={15}/> {tr('YOUR LESSON','درسك')}</span><span>01</span></div><div className="sculpture-title">{tr('A new way','طريقة جديدة')}<br/>{tr('to understand.','للفهم.')}</div><div className="sculpture-lines"><i/><i/><i/></div><div className="sculpture-format"><BookOpen size={18}/><span>{tr('Clearer reading','قراءة أوضح')}</span><Check size={15}/></div><div className="sculpture-format"><Layers size={18}/><span>{tr('Better recall','مراجعة أسهل')}</span><Check size={15}/></div></div><div className="sculpture-tag"><Sparkles size={18}/>{tr('Ready for new possibilities','جاهز لإمكانات جديدة')}</div></div></section>
 <div className="metric-strip">{[[FileText,lessons.length,tr('Lessons in your library','دروس في مكتبتك'),'01'],[Layers,versions,tr('Saved versions','نسخ محفوظة'),'02'],[BookOpen,drafts,tr('Ready to adapt','جاهزة للتكييف'),'03']].map(([Icon,num,label,index])=><div className="metric" key={index}><span className="metric-index">{index}</span><div><strong><CountUp value={num} pad={2}/></strong><span>{label}</span></div><Icon size={23}/></div>)}</div>
 <QuickAsk/>
 <LiveClassCreate/>
 <div className="dashboard-columns"><section className="panel recent-panel"><div className="section-heading"><div><p className="section-kicker">{tr('PICK UP WHERE YOU LEFT OFF','أكمل من حيث توقّفت')}</p><h2>{tr('Recent lessons','الدروس الأخيرة')}</h2></div><Link className="text-link" to="/app/history">{tr('View all','عرض الكل')}<ArrowUpRight size={15}/></Link></div>{lessons.length?lessons.slice(0,4).map(l=><LessonRow key={l.id} lesson={l}/>):<Empty title={tr('Your library starts here','مكتبتك تبدأ من هنا')} text={tr('Add a lesson and keep every version in one place.','أضف درساً واحتفظ بنسخه في مكان واحد.')} to="/app/upload" label={tr('Add your first lesson','أضف درسك الأول')}/>}</section>
 <aside className="journey-panel"><p className="section-kicker">{tr('A LITTLE SUPPORT GOES A LONG WAY','دعم بسيط يصنع فرقاً')}</p><h2>{tr('From your lesson,','من درسك،')}<br/><span>{tr('to their next discovery.','إلى اكتشافهم القادم.')}</span></h2><ol>{steps.map(([Icon,title,description],i)=><li key={title}><span className="journey-icon"><Icon size={17}/></span><div><strong>{title}</strong><p>{description}</p></div><span className="journey-number">0{i+1}</span></li>)}</ol>{DEMO?<button className="text-link" onClick={sample}>{tr('Open sample lesson','افتح الدرس النموذجي')}<ArrowRight size={16}/></button>:<Link className="text-link" to="/app/upload">{tr('Start with a lesson','ابدأ بدرس')}<ArrowRight size={16}/></Link>}</aside></div></>
}
