import {Volume2,Square,ArrowLeft} from 'lucide-react'
/* Resource effects reset loading while synchronizing with remote data. */
/* eslint-disable react-hooks/set-state-in-effect */
import {useEffect,useState,useRef} from 'react'
import {Link,useParams} from 'react-router-dom'
import {AlignLeft,ListChecks,Layers,BookOpen,Check,ChevronLeft,ChevronRight,RotateCcw} from '../components/Icons'
import {useTabsKnob} from '../hooks/useTabsKnob'
import {useApp} from '../context/AppContext'
import {Empty,Busy,ErrorBox} from '../components/UI'
import PdfViewer from '../components/PdfViewer'
import {fileKind} from '../data/demo'
import {FileText as PdfIcon,Layers as LayersIcon,Trophy as TrophyIcon} from 'lucide-react'
import {outputText} from '../data/demo'
import {api} from '../services/api'
import {FlipCard} from '../components/Motion'
import {useQuizFeedback} from '../hooks/useMotion'
const CONTENT_TYPES=['summary','quiz','flashcards','simplified']
const icons={summary:AlignLeft,quiz:ListChecks,flashcards:Layers,simplified:BookOpen}
export default function StudentLesson(){const{id}=useParams(),{tr}=useApp(),[lesson,setLesson]=useState(null),[mode,setMode]=useState('summary'),[attempts,setAttempts]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[retry,setRetry]=useState(0),[speaking,setSpeaking]=useState(false)
 const tabsRef=useRef(null),[pdfOpen,setPdfOpen]=useState(false)
 useTabsKnob(tabsRef,[mode,lesson])
 const names={summary:tr('Summary','الملخص'),quiz:tr('Quiz','الأسئلة'),flashcards:tr('Flashcards','بطاقات المراجعة'),simplified:tr('Simplified','نسخة مبسّطة')}
 useEffect(()=>{let active=true;setLoading(true);setError('')
  Promise.all([api.studentLesson(id),api.quizAttempts(id).catch(()=>[])]).then(([lessonData,attemptRows])=>{if(!active)return;setLesson(lessonData);setMode(CONTENT_TYPES.find(type=>lessonData.outputs[type])||'summary');setAttempts(attemptRows)}).catch(()=>{if(active)setError(tr('Could not load this lesson.','تعذّر تحميل هذا الدرس.'))}).finally(()=>{if(active)setLoading(false)})
  return()=>{active=false}
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[id,retry])
 useEffect(()=>{window.speechSynthesis?.cancel();setSpeaking(false);return()=>window.speechSynthesis?.cancel()},[id,mode])
 function speak(){if(speaking){window.speechSynthesis?.cancel();setSpeaking(false);return}const engine=window.speechSynthesis;if(!engine){setError(tr('Speech is unavailable in this browser.','القراءة الصوتية غير متاحة في هذا المتصفح.'));return}const voice=engine.getVoices().find(v=>v.lang.startsWith(lesson.lang));if(!voice){setError(tr('No voice for this lesson language is installed.','لا يوجد صوت مثبت بلغة هذا الدرس.'));return}const speech=new SpeechSynthesisUtterance(outputText(lesson.outputs[mode]));speech.voice=voice;speech.rate=.9;speech.onend=()=>setSpeaking(false);speech.onerror=()=>setSpeaking(false);setSpeaking(true);engine.speak(speech)}
 async function recordAttempt(score,total){setError('');try{const attempt=await api.submitQuizAttempt(id,{score,total});setAttempts(old=>[attempt,...old]);setNotice(tr('Score saved.','حُفظت النتيجة.'));return true}catch{setError(tr('Could not save your score. Please try again.','تعذّر حفظ نتيجتك. حاول مجدداً.'));return false}}
 if(error&&!lesson)return <><ErrorBox>{error}</ErrorBox><button className="soft-btn" onClick={()=>setRetry(n=>n+1)}>{tr('Retry','إعادة المحاولة')}</button></>
 if(loading)return <Busy>{tr('Loading lesson…','جارٍ تحميل الدرس…')}</Busy>
 if(!lesson)return <Empty title={tr('Lesson not found','الدرس غير موجود')} text={tr('This lesson may no longer be shared with you.','قد لا يكون هذا الدرس مشاركاً معك بعد الآن.')} to="/app/student" label={tr('Back to lessons','العودة إلى الدروس')}/>
 const content=lesson.outputs[mode]
 const visibleTypes=CONTENT_TYPES.filter(type=>lesson.outputs[type])
 const bestScore=attempts.reduce((best,attempt)=>!best||attempt.score/attempt.total>best.score/best.total?attempt:best,null)
 return <><Link className="mb-5 inline-flex items-center gap-2 text-sm text-[#687457]" to="/app/student"><ArrowLeft size={16}/>{tr('Back to lessons','العودة إلى الدروس')}</Link><section className="sl-hero"><div className="sl-hero-copy"><p className="sl-eyebrow"><span aria-hidden="true"/>{tr('SHARED LESSON','درس مشارك')}</p><h1 dir="auto">{lesson.title}</h1><div className="sl-meta"><span><PdfIcon size={14}/>{lesson.fileName}</span><span><LayersIcon size={14}/>{Object.keys(lesson.outputs||{}).length} {tr('materials','مواد')}</span>{attempts.length>0&&<span><TrophyIcon size={14}/>{tr('Best score','أفضل درجة')}: {Math.max(...attempts.map(a=>a.percentage??Math.round(a.score/a.total*100)))}%</span>}</div></div><div className="sl-hero-actions"><Link className="sl-tutor-link" to="/app/student/tutor">{tr('Ask the Study Tutor','اسأل مساعد التعلّم')}<ArrowLeft size={16}/></Link><button type="button" className="sl-pdf" onClick={()=>setPdfOpen(true)}><span className="sl-pdf-icon" aria-hidden="true"><PdfIcon size={20}/></span><span><strong>{fileKind(lesson.fileName)==='video'?tr('Original video','الفيديو الأصلي'):tr('Original PDF','ملف PDF الأصلي')}</strong><small>{tr('Open the lesson as your teacher shared it','افتح الدرس كما شاركه معلّمك')}</small></span></button></div></section>{pdfOpen&&<PdfViewer lessonId={lesson.id} fileName={lesson.fileName} onClose={()=>setPdfOpen(false)}/>}<div className="studio-tabs" ref={tabsRef} role="group" aria-label={tr('Content type','نوع المحتوى')}><span className="tabs-knob" aria-hidden="true"/>{(visibleTypes.length?visibleTypes:[mode]).map(type=>{const Icon=icons[type];return <button key={type} className={mode===type?'active':''} aria-pressed={mode===type} onClick={()=>setMode(type)}><Icon size={18}/>{names[type]}{lesson.outputs[type]&&<Check size={13}/>}</button>})}</div><ErrorBox>{error}</ErrorBox>{notice&&<p className="success" role="status">{notice}</p>}<section className="panel result-panel"><div className="section-heading"><h2>{names[mode]}</h2>{content&&mode!=='quiz'&&<button className="soft-btn" onClick={speak}>{speaking?<Square size={16}/>:<Volume2 size={16}/>} {speaking?tr('Stop reading','إيقاف القراءة'):tr('Read aloud','قراءة صوتية')}</button>}{mode==='quiz'&&bestScore&&<span className="pill">{tr('Best score','أفضل نتيجة')}: {bestScore.score} / {bestScore.total}</span>}</div>{!content?<Empty title={tr('Not shared yet','لم تتم مشاركته بعد')} text={tr('Your teacher has not created this version yet.','لم يُنشئ معلمك هذه النسخة بعد.')}/>:mode==='quiz'&&Array.isArray(content)&&content.length?<StudentQuiz key={`${id}-${mode}`} questions={content} tr={tr} onFinish={recordAttempt} passed={attempts.some(a=>a.passed)}/>:mode==='flashcards'&&Array.isArray(content)&&content.length?<StudentCards cards={content} tr={tr}/>:<div className="reading-text" dir="auto">{outputText(content)}</div>}</section></>}
function StudentQuiz({questions,tr,onFinish,passed}){const[answers,setAnswers]=useState({}),[checked,setChecked]=useState(false),[saving,setSaving]=useState(false)
 const score=questions.filter((q,i)=>answers[i]===q.correct).length,ref=useQuizFeedback(checked,checked&&score===questions.length)
 async function check(){if(saving)return;setSaving(true);const score=questions.filter((q,i)=>answers[i]===q.correct).length;if(await onFinish(score,questions.length))setChecked(true);setSaving(false)}
 if(passed&&!checked)return <div className="success">{tr("You have passed this quiz. Your result is saved.","اجتزت هذا الاختبار. نتيجتك محفوظة.")}</div>
 return <div className="quiz-stack" ref={ref}>{questions.map((q,i)=><fieldset key={i}><legend><span>{i+1}</span>{q.q}</legend>{q.options.map((option,j)=><label key={j} className={`${answers[i]===j?'selected':''} ${checked&&j===q.correct?'correct':''} ${checked&&answers[i]===j&&j!==q.correct?'wrong':''}`}><input type="radio" name={`question-${i}`} checked={answers[i]===j} disabled={checked||saving} onChange={()=>setAnswers({...answers,[i]:j})}/>{option}{checked&&j===q.correct&&<Check size={16}/>}</label>)}{checked&&q.explanation&&<p className="mt-3 rounded-xl bg-[#eef3e3] p-4 text-sm leading-7">{q.explanation}</p>}</fieldset>)}{checked?<div className="success quiz-score" role="status"><span>{tr('Your score','نتيجتك')}: <b>{score} / {questions.length}</b></span>{!passed&&<button className="soft-btn" onClick={()=>{setAnswers({});setChecked(false)}}><RotateCcw size={15}/>{tr('Try again','حاول مجدداً')}</button>}</div>:<button className="primary-btn full" disabled={saving||Object.keys(answers).length!==questions.length} onClick={check}>{saving?tr('Saving…','جارٍ الحفظ…'):tr('Check answers','تحقّق من الإجابات')}</button>}</div>}
function StudentCards({cards,tr}){const[index,setIndex]=useState(0),[flipped,setFlipped]=useState(false),[direction,setDirection]=useState(1);function next(delta){setDirection(delta);setIndex((index+delta+cards.length)%cards.length);setFlipped(false)}return <div className="flashcard-view"><p className="muted">{tr('Card','البطاقة')} {index+1} / {cards.length}</p><FlipCard key={index} direction={direction} front={cards[index]?.front} back={cards[index]?.back} flipped={flipped} onFlip={()=>setFlipped(!flipped)} labels={{flip:tr('Flip flashcard','اقلب البطاقة'),term:tr('TERM','المصطلح'),answer:tr('ANSWER','الإجابة'),hint:tr('Click to flip','اضغط لقلب البطاقة')}}/><div className="flashcard-controls"><button className="soft-btn" onClick={()=>next(-1)}><ChevronLeft size={18}/>{tr('Previous','السابق')}</button><button className="soft-btn" onClick={()=>next(1)}>{tr('Next','التالي')}<ChevronRight size={18}/></button></div></div>}
