import {useEffect,useState} from 'react'
import {useParams} from 'react-router-dom'
import {AlignLeft,ListChecks,Layers,BookOpen,Check,ChevronLeft,ChevronRight,RotateCcw} from '../components/Icons'
import {useApp} from '../context/AppContext'
import {PageHeading,Empty,Busy,ErrorBox} from '../components/UI'
import {outputText} from '../data/demo'
import {api} from '../services/api'
const CONTENT_TYPES=['summary','quiz','flashcards','simplified']
const icons={summary:AlignLeft,quiz:ListChecks,flashcards:Layers,simplified:BookOpen}
export default function StudentLesson(){const{id}=useParams(),{tr}=useApp(),[lesson,setLesson]=useState(null),[mode,setMode]=useState('summary'),[attempts,setAttempts]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const names={summary:tr('Summary','الملخص'),quiz:tr('Quiz','الأسئلة'),flashcards:tr('Flashcards','بطاقات المراجعة'),simplified:tr('Simplified','نسخة مبسّطة')}
 useEffect(()=>{let active=true;setLoading(true);setError('')
  Promise.all([api.studentLesson(id),api.quizAttempts(id).catch(()=>[])]).then(([lessonData,attemptRows])=>{if(!active)return;setLesson(lessonData);setAttempts(attemptRows)}).catch(()=>{if(active)setError(tr('Could not load this lesson.','تعذّر تحميل هذا الدرس.'))}).finally(()=>{if(active)setLoading(false)})
  return()=>{active=false}
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[id])
 async function recordAttempt(score,total){try{const attempt=await api.submitQuizAttempt(id,{score,total});setAttempts(old=>[attempt,...old]);setNotice(tr('Score saved.','حُفظت النتيجة.'))}catch{setError(tr('Could not save your score. Please try again.','تعذّر حفظ نتيجتك. حاول مجدداً.'))}}
 if(loading)return <Busy>{tr('Loading lesson…','جارٍ تحميل الدرس…')}</Busy>
 if(!lesson)return <Empty title={tr('Lesson not found','الدرس غير موجود')} text={tr('This lesson may no longer be shared with you.','قد لا يكون هذا الدرس مشاركاً معك بعد الآن.')} to="/app/student" label={tr('Back to lessons','العودة إلى الدروس')}/>
 const content=lesson.outputs[mode]
 const bestScore=attempts.reduce((best,attempt)=>!best||attempt.score/attempt.total>best.score/best.total?attempt:best,null)
 return <><PageHeading eyebrow={tr('SHARED LESSON','درس مشارك')} title={lesson.title} description={lesson.fileName}/><div className="studio-tabs" role="group" aria-label={tr('Content type','نوع المحتوى')}>{CONTENT_TYPES.map(type=>{const Icon=icons[type];return <button key={type} className={mode===type?'active':''} aria-pressed={mode===type} onClick={()=>setMode(type)}><Icon size={18}/>{names[type]}{lesson.outputs[type]&&<Check size={13}/>}</button>})}</div><ErrorBox>{error}</ErrorBox>{notice&&<p className="success" role="status">{notice}</p>}<section className="panel result-panel"><div className="section-heading"><h2>{names[mode]}</h2>{mode==='quiz'&&bestScore&&<span className="pill">{tr('Best score','أفضل نتيجة')}: {bestScore.score} / {bestScore.total}</span>}</div>{!content?<Empty title={tr('Not shared yet','لم تتم مشاركته بعد')} text={tr('Your teacher has not created this version yet.','لم يُنشئ معلمك هذه النسخة بعد.')}/>:mode==='quiz'&&Array.isArray(content)?<StudentQuiz questions={content} tr={tr} onFinish={recordAttempt}/>:mode==='flashcards'&&Array.isArray(content)?<StudentCards cards={content} tr={tr}/>:<div className="reading-text">{outputText(content)}</div>}</section></>}
function StudentQuiz({questions,tr,onFinish}){const[answers,setAnswers]=useState({}),[checked,setChecked]=useState(false)
 function check(){const score=questions.filter((q,i)=>answers[i]===q.correct).length;setChecked(true);onFinish(score,questions.length)}
 return <div className="quiz-stack">{questions.map((q,i)=><fieldset key={i}><legend><span>{i+1}</span>{q.q}</legend>{q.options.map((option,j)=><label key={j} className={`${answers[i]===j?'selected':''} ${checked&&j===q.correct?'correct':''}`}><input type="radio" name={`question-${i}`} checked={answers[i]===j} disabled={checked} onChange={()=>setAnswers({...answers,[i]:j})}/>{option}{checked&&j===q.correct&&<Check size={16}/>}</label>)}</fieldset>)}{checked?<div className="success" role="status">{tr('Your score','نتيجتك')}: {questions.filter((q,i)=>answers[i]===q.correct).length} / {questions.length}<button className="soft-btn" onClick={()=>{setAnswers({});setChecked(false)}}><RotateCcw size={15}/>{tr('Try again','حاول مجدداً')}</button></div>:<button className="primary-btn full" disabled={Object.keys(answers).length!==questions.length} onClick={check}>{tr('Check answers','تحقّق من الإجابات')}</button>}</div>}
function StudentCards({cards,tr}){const[index,setIndex]=useState(0),[flipped,setFlipped]=useState(false);function next(delta){setIndex((index+delta+cards.length)%cards.length);setFlipped(false)}return <div className="flashcard-view"><p className="muted">{tr('Card','البطاقة')} {index+1} / {cards.length}</p><button className={`flashcard ${flipped?'flipped':''}`} onClick={()=>setFlipped(!flipped)} aria-label={tr('Flip flashcard','اقلب البطاقة')}><span>{flipped?tr('ANSWER','الإجابة'):tr('TERM','المصطلح')}</span><strong className="reading-text">{flipped?cards[index].back:cards[index].front}</strong><small>{tr('Click to flip','اضغط لقلب البطاقة')} ↻</small></button><div className="flashcard-controls"><button className="soft-btn" onClick={()=>next(-1)}><ChevronLeft size={18}/>{tr('Previous','السابق')}</button><button className="soft-btn" onClick={()=>next(1)}>{tr('Next','التالي')}<ChevronRight size={18}/></button></div></div>}
