/* Resource effects reset loading while synchronizing with remote data. */
/* eslint-disable react-hooks/set-state-in-effect */
import {useEffect,useState} from 'react'
import {UpcomingClasses} from '../components/LiveClassCard'
import {Link} from 'react-router-dom'
import {ArrowUpRight,BookOpen,Search,RefreshCw,Layers,AlignLeft,ListChecks,Volume2,Upload} from 'lucide-react'
import {CountUp} from '../components/Motion'
import QuickAsk from '../components/QuickAsk'
import {useApp} from '../context/AppContext'
import {PageHeading,Empty,Busy,ErrorBox,LessonRow} from '../components/UI'
import {api} from '../services/api'
export default function StudentDashboard(){
 const{tr,lang,user,lessons:ownLessons}=useApp(),[lessons,setLessons]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[retry,setRetry]=useState(0)
 // Translation is read for the request; locale changes do not refetch data.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{let active=true;setLoading(true);setError('');api.studentLessons().then(rows=>{if(active)setLessons(rows)}).catch(()=>{if(active)setError(tr('Could not load your shared lessons.','تعذّر تحميل الدروس المشاركة.'))}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[retry])
 const filtered=lessons.filter(l=>l.title.toLocaleLowerCase().includes(query.toLocaleLowerCase()))
 return <><PageHeading eyebrow={tr('YOUR LEARNING SPACE','مساحة تعلّمك')} title={`${new Date().getHours()<12?tr('Good morning','صباح الخير'):new Date().getHours()<18?tr('Good afternoon','نهارك سعيد'):tr('Good evening','مساء الخير')}${lang==='en'?',':'،'} ${(user.name||'').split(' ')[0]}`} description={tr('One small step. A new possibility.','خطوة صغيرة تفتح لك إمكانات جديدة.')}/>
 <section className="student-banner mb-7 flex flex-col gap-6 rounded-3xl border border-[#e1e7d5] p-6 md:flex-row md:items-center md:justify-between md:p-9"><div className="max-w-xl"><span className="mb-4 inline-flex rounded-full bg-white/80 px-3 py-1 text-xs font-semibold tracking-wide">AdaptEd · {tr('MADE FOR YOUR PACE','تعلّم على راحتك')}</span><h2 className="mb-3 text-3xl font-semibold tracking-tight">{tr('Make room for your next discovery.','مساحة لاكتشافك القادم.')}</h2><p className="text-sm leading-7 text-[#58614e]">{tr('Your own lessons and lessons shared with you are together in one place.','دروسك الخاصة والدروس المشاركة وياك بمكان واحد.')}</p></div><div className="flex gap-4"><div className="rounded-2xl bg-white/80 p-5"><BookOpen size={20}/><strong className="mt-3 block text-3xl">{loading?'—':<CountUp value={lessons.length}/>}</strong><span className="text-sm">{tr('Shared lessons','دروس مشاركة')}</span></div><div className="rounded-2xl bg-white/80 p-5"><Layers size={20}/><strong className="mt-3 block text-3xl">{loading?'—':<CountUp value={lessons.reduce((n,l)=>n+l.generatedCount,0)}/>}</strong><span className="text-sm">{tr('Learning materials','مواد تعليمية')}</span></div></div></section>
 <nav className="student-shortcuts" aria-label={tr('Learning shortcuts','اختصارات التعلّم')}><Link to="/app/student/tools/generate"><AlignLeft size={19}/>{tr('Generate','التوليد')}</Link><Link to="/app/student/tools/quiz"><ListChecks size={19}/>{tr('Quiz','الاختبارات')}</Link><Link to="/app/student/tools/flashcards"><Layers size={19}/>{tr('Flashcards','البطاقات')}</Link><Link to="/app/student/tutor"><BookOpen size={19}/>{tr('Study Tutor','مساعد التعلّم')}</Link></nav><QuickAsk/><UpcomingClasses/><section className="own-lessons" aria-labelledby="own-lessons-title"><div className="own-head"><div><p className="own-eyebrow">{tr('YOUR OWN LESSONS','دروسك الخاصة')}</p><h2 id="own-lessons-title">{tr('Study your own material','ذاكر من موادك الخاصة')}</h2><p>{tr('Upload a PDF or a video and create summaries, quizzes and flashcards for yourself.','ارفع ملف PDF أو فيديو وأنشئ لنفسك ملخصات واختبارات وبطاقات مراجعة.')}</p></div><div className="own-actions">{ownLessons.length>0&&<Link className="own-all" to="/app/student/library">{tr('View all & manage','عرض الكل وإدارتها')}</Link>}<Link className="own-upload" to="/app/student/upload"><Upload size={17}/>{tr('Upload lesson','رفع درس')}</Link></div></div>{ownLessons.length?<div className="own-list">{ownLessons.slice(0,6).map(l=><LessonRow key={l.id} lesson={l}/>)}</div>:<div className="own-empty"><span aria-hidden="true"><Upload size={20}/></span><p>{tr('No lessons of your own yet. Upload your first one to get started.','لا توجد دروس خاصة بعد. ارفع أول درس لتبدأ.')}</p></div>}</section><div className="student-layout"><section aria-label={tr('My lessons','دروسي')}><div className="mb-5 flex flex-wrap items-center justify-between gap-4"><h2 className="text-xl font-semibold">{tr('Shared with you','مشاركة معك')}</h2><div className="flex w-full gap-2 sm:w-auto"><label className="flex min-w-0 flex-1 items-center gap-2 rounded-xl border border-[#dfe4d5] bg-white px-3"><Search size={18}/><input className="w-full border-0! bg-transparent! py-3!" aria-label={tr('Search shared lessons','البحث في الدروس المشاركة')} placeholder={tr('Search shared lessons…','ابحث في الدروس المشاركة…')} value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="soft-btn" disabled={loading} aria-label={tr('Refresh lessons','تحديث الدروس')} onClick={()=>setRetry(n=>n+1)}><RefreshCw size={18}/></button></div></div><ErrorBox>{error}</ErrorBox>
 {loading?<Busy>{tr('Loading your lessons…','جارٍ تحميل دروسك…')}</Busy>:error?<button className="soft-btn" onClick={()=>setRetry(n=>n+1)}>{tr('Retry','إعادة المحاولة')}</button>:filtered.length?<div className="grid gap-4 sm:grid-cols-2">{filtered.map((lesson,i)=><Link key={lesson.id} className="learning-card flex min-w-0 flex-col rounded-2xl border border-[#e1e5d9] bg-white p-6 text-inherit no-underline" to={`/app/student/lesson/${lesson.id}`}><div className="mb-7 flex items-center justify-between"><span className={`rounded-xl p-3 ${i%3===0?'bg-[#eaf2d6]':i%3===1?'bg-[#eee9f7]':'bg-[#e4eff5]'}`}><BookOpen size={23}/></span><ArrowUpRight size={19}/></div><h3 className="mb-2 break-words text-lg font-semibold">{lesson.title}</h3><p className="mb-5 truncate text-xs text-[#727967]">{lesson.fileName}</p><div className="mt-auto flex items-center justify-between border-t border-[#edf0e5] pt-4 text-xs text-[#626b55]"><span>{lesson.generatedCount} {tr('materials','مواد')}</span><span>{lesson.assignedAt||lesson.createdAt?new Date(lesson.assignedAt||lesson.createdAt).toLocaleDateString(lang==='en'?'en-GB':lang==='ckb'?'ckb-IQ':'ar-IQ'):''}</span></div></Link>)}</div>:<Empty title={query?tr('No matching lessons','لا توجد نتائج مطابقة'):tr('No lessons shared yet.','لا توجد دروس مشاركة بعد.')} text={query?tr('Try a different search.','جرّب كلمات بحث أخرى.'):tr('Your teacher will share adapted lessons here.','سيشارك معلمك الدروس المكيّفة هنا.')}/>}</section>
 <aside className="study-path" aria-labelledby="study-path-title"><p className="study-path-note" aria-hidden="true">{tr('Read it. Hear it. Get it.','اقرأ. اسمع. افهم.')}</p><h2 id="study-path-title">{tr('How to study a lesson','كيف تذاكر درسك')}</h2><ol>{[[AlignLeft,tr('Start with the summary','ابدأ بالملخص'),tr('Get the big picture in a few calm minutes.','خذ الفكرة العامة بدقائق هادئة.')],[Volume2,tr('Listen if it helps','استمع إذا كان ذلك أسهل'),tr('Use Read aloud to hear the lesson at your pace.','استخدم القراءة الصوتية لتسمع الدرس على راحتك.')],[ListChecks,tr('Test yourself','اختبر نفسك'),tr('Try the quiz. Every answer shows you what to review.','حلّ الأسئلة. كل إجابة توضّح لك ما تحتاج مراجعته.')],[Layers,tr('Review with flashcards','راجع بالبطاقات'),tr('Flip the cards until the ideas stick.','اقلب البطاقات حتى تثبت الأفكار.')]].map(([Icon,title,text])=><li key={title}><span className="study-path-icon"><Icon size={18}/></span><div><strong>{title}</strong><p>{text}</p></div></li>)}</ol></aside></div></>
}
