import {useEffect,useState} from 'react'
import {Link} from 'react-router-dom'
import {ArrowUpRight,Check,Copy,Mail,Plus,Sparkles} from 'lucide-react'
import {useApp} from '../context/AppContext'
import PublicShell from '../components/PublicShell'

const EMAIL='adaptedteam.3@gmail.com'
const TEAM=[{name:'Lubna Mohammed Eyad',color:'sky',motif:'arch',hair:'waves'},{name:'Zahraa Qasim',color:'sage',motif:'orbit',hair:'bob'},{name:'Amani Khalid',color:'pink',motif:'fold',hair:'ponytail'}]
function TeamAvatar({hair}){
 return <svg className="sp-avatar" viewBox="0 0 160 180" fill="none" aria-hidden="true" focusable="false">
  <circle cx="80" cy="85" r="66" fill="#fff" fillOpacity=".3"/>
  {hair==='waves'&&<path d="M44 67c0-26 14-41 36-41s37 15 37 41v43c0 13-12 17-18 12H60c-12 4-19-5-17-15Z" fill="#614b42"/>}
  {hair==='bob'&&<path d="M42 65c0-26 15-40 38-40 24 0 38 17 38 40l4 40c-8 16-76 16-84 0Z" fill="#493e39"/>}
  {hair==='ponytail'&&<><ellipse cx="122" cy="78" rx="15" ry="32" transform="rotate(-16 122 78)" fill="#685044"/><path d="M44 68c-2-28 13-43 36-43s39 15 37 43l-7 23H49Z" fill="#685044"/></>}
  <path d="M37 149c0-24 17-36 43-36s43 12 43 36v6c-22 9-64 9-86 0Z" className="sp-avatar-shirt"/>
  <path d="M70 105v11c0 11 20 11 20 0v-11" fill="#efc8ad"/>
  <path d="m65 117 15 10 15-10" stroke="#fff" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/>
  <ellipse cx="49" cy="79" rx="5" ry="7" fill="#f6d5bc"/><ellipse cx="111" cy="79" rx="5" ry="7" fill="#f6d5bc"/>
  <path d="M50 65c0-18 60-18 60 0v18c0 19-13 32-30 32S50 102 50 83Z" fill="#f9ddc6"/>
  {hair==='waves'&&<><path d="M47 70c-5-25 12-36 33-36 20 0 36 12 33 37-17-3-28-13-32-23-8 13-19 19-34 22Z" fill="#614b42"/><path d="m50 65-1 35m62-35 1 35" stroke="#614b42" strokeWidth="7" strokeLinecap="round"/><path d="m48 56 7-4" stroke="#96c8e5" strokeWidth="5" strokeLinecap="round"/></>}
  {hair==='bob'&&<><path d="M48 66c-1-22 12-33 32-33s34 11 33 34c-16-2-27-9-32-18-8 11-20 16-33 17Z" fill="#493e39"/><path d="M50 44c17-13 41-13 59 1" stroke="#b8d59e" strokeWidth="5" strokeLinecap="round"/></>}
  {hair==='ponytail'&&<><path d="M47 68c-3-24 12-35 33-35s36 13 34 36c-17-4-28-15-34-22-5 11-18 18-33 21Z" fill="#685044"/><path d="m113 47 12-9 1 13-11-1-9 8-3-12Z" fill="#e8a6bf"/><circle cx="114" cy="48" r="3" fill="#f7cfde"/></>}
  <circle cx="67" cy="81" r="2.5" fill="#51423b"/><circle cx="94" cy="81" r="2.5" fill="#51423b"/>
  <ellipse cx="60" cy="89" rx="6" ry="3.5" fill="#efb6af" fillOpacity=".65"/><ellipse cx="101" cy="89" rx="6" ry="3.5" fill="#efb6af" fillOpacity=".65"/>
  <path d="M76 93q4 5 8 0" stroke="#b87970" strokeWidth="2" strokeLinecap="round"/>
 </svg>
}
export default function Support(){
 const {tr,lang,user}=useApp(),[copyState,setCopyState]=useState('idle')
 useEffect(()=>{document.title=`${lang==='ar'?'الدعم والفريق':'Support & Team'} · AdaptEd`},[lang])
 useEffect(()=>{if(copyState==='idle')return;const timer=setTimeout(()=>setCopyState('idle'),4500);return()=>clearTimeout(timer)},[copyState])
 async function copyEmail(){try{await navigator.clipboard.writeText(EMAIL);setCopyState('copied')}catch{setCopyState('failed')}}
 const faqs=[
  [tr('Do I need an account to reach you?','هل أحتاج حسابًا حتى أتواصل؟'),tr('You do not need an AdaptEd account. Contact our team from your own email. Gmail may ask you to sign in to your Google account.','ما تحتاج حساب AdaptEd. تواصل معنا من إيميلك الشخصي. Gmail ممكن يطلب تسجيل دخول بحساب Google الخاص بك.')],
  [tr('What should I include in a problem report?','شنو أكتب إذا واجهتني مشكلة؟'),tr('Tell us which page you were on, the steps you tried, and what happened. Your browser or device and a screenshot can help.','اذكر الصفحة، والخطوات اللي جرّبتها، وشنو صار بعدها. اسم المتصفح أو الجهاز وصورة للمشكلة يساعدونا نفهمها.')],
  [tr('Can I use another email service?','أكدر أستخدم بريد غير Gmail؟'),tr('Of course. Copy our email address and paste it into the recipient field in your preferred email service. Write your message and send it there.','أكيد. انسخ عنواننا والصقه بخانة المستلم بخدمة البريد اللي تستخدمها. اكتب رسالتك وأرسلها من هناك.')]
 ]
 return <PublicShell className="support-shell"><div className="support-page" dir={lang==='en'?'ltr':'rtl'}>
  <section className="sp-hero" aria-labelledby="support-title"><div className="sp-intro"><p className="sp-kicker"><span/>{tr('SUPPORT & TEAM','الدعم والفريق')}</p><h1 id="support-title">{tr('Built with care.','صنعناه باهتمام.')}<br/><em>{tr('Here for you.','ونحن هنا لأجلك.')}</em></h1><p className="sp-lead">{tr('Behind every lesson is a learner. Behind AdaptEd is a team that cares about their journey.','وراء كل درس متعلّم. ووراء AdaptEd فريق يهتم برحلته، ويؤمن أن لكل شخص طريقته في التعلّم.')}</p><div className="sp-hero-actions"><a className="sp-button" href="#support-contact">{tr('Talk to our team','تواصل مع الفريق')}<ArrowUpRight size={18}/></a><a className="sp-text-link" href="#support-team">{tr('Meet the people','تعرّف علينا')}<span aria-hidden="true">↓</span></a></div><div className="sp-signature"><div aria-hidden="true">{TEAM.map(member=><span className={`sp-avatar-${member.color}`} key={member.name}><TeamAvatar hair={member.hair}/></span>)}</div><p>{tr('Three minds. One shared purpose.','ثلاثة عقول. هدف واحد.')}<small>{tr('Making room for every learner.','مساحة لكل متعلّم.')}</small></p></div></div>
   <div className="sp-art" aria-hidden="true"><div className="sp-art-grid"/><div className="sp-orbit"/><div className="sp-orbit sp-orbit-two"/><span className="sp-art-star">✳</span><span className="sp-art-caption">{tr('A HUMAN CONNECTION','تواصل إنساني')}</span><div className="sp-letter-back"/><div className="sp-letter"><span className="sp-letter-top"><b>AdaptEd</b><Mail size={24}/></span><p>{tr('A little help.','مساعدة صغيرة.')}<br/><em>{tr('A world of possibility.','وإمكانات كبيرة.')}</em></p><div className="sp-letter-rule"/><span className="sp-letter-sign">{tr('From our team, to you.','من فريقنا، إليك.')}</span><span className="sp-letter-stamp">AE<Sparkles size={13}/></span></div><div className="sp-art-note">{tr('Learning connects us.','التعلّم يجمعنا.')}</div><span className="sp-art-bottom">{tr('PEOPLE MAKE THE DIFFERENCE','الأثر يبدأ بالناس')}</span></div>
  </section>
  <section className="sp-team" id="support-team" aria-labelledby="team-title"><div className="sp-section-heading"><div><p className="sp-kicker">{tr('THE PEOPLE BEHIND ADAPTED','الفريق وراء ADAPTED')}</p><h2 id="team-title">{tr('Different minds.','أفكار مختلفة.')}<br/><span>{tr('One meaningful idea.','وفكرة تجمعنا.')}</span></h2></div><p>{tr('A shared belief brought us together: learning should make space for everyone. Meet the team bringing AdaptEd to life.','جمعنا إيمان واحد: التعلّم لازم يتّسع للجميع. هذا هو الفريق الذي حوّل فكرة AdaptEd إلى تجربة بين يديك.')}</p></div><div className="sp-team-grid">{TEAM.map(member=><article key={member.name} className={`sp-member sp-member-${member.motif} sp-avatar-${member.color}`}><div className="sp-member-art" aria-hidden="true"><div className="sp-member-lines"><i/><i/><i/></div><TeamAvatar hair={member.hair}/><span className="sp-member-mark"><Plus size={20}/></span></div><div className="sp-member-info"><p>{tr('ADAPTED TEAM','فريق ADAPTED')}</p><h3 dir="ltr">{member.name}</h3><span className="sp-member-line"/></div></article>)}</div><div className="sp-team-footnote"><span aria-hidden="true">✳</span><p>{tr('Built together. For the way you learn.','صنعناه معًا. لطريقتك في التعلّم.')}</p><b>AdaptEd</b></div></section>
  <section className="sp-contact" id="support-contact" aria-labelledby="contact-title"><div className="sp-contact-top"><div><p className="sp-kicker">{tr('ONE INBOX. THE WHOLE TEAM.','بريد واحد. للفريق كله.')}</p><h2 id="contact-title">{tr('Good conversations','كل حوار جميل')}<br/><em>{tr('start with hello.','يبدأ بمرحبًا.')}</em></h2></div><Mail size={76} strokeWidth={1} aria-hidden="true"/></div><p className="sp-contact-lead">{tr('A question, an idea, or something we can improve. We’d love to hear from you.','سؤال، اقتراح، أو شيء نقدر نحسّنه. يسعدنا نسمع منك.')}</p><div className="sp-email-row"><span className="sp-email" dir="ltr">{EMAIL}</span><button type="button" className="sp-copy" onClick={copyEmail}>{copyState==='copied'?<Check size={17}/>:<Copy size={17}/>}<span>{copyState==='copied'?tr('Copied','تم النسخ'):tr('Copy email','نسخ الإيميل')}</span></button></div><p className="sp-copy-status" role="status" aria-live="polite">{copyState==='copied'?tr('Email address copied to your clipboard.','تم نسخ عنوان البريد.'):copyState==='failed'?tr('Copy is unavailable here. Select the address above and copy it manually.','النسخ غير متاح هنا. حدّد عنوان البريد أعلاه وانسخه يدويًا.'):''}</p><div className="sp-gmail-action"><a className="sp-button sp-button-light" href={`https://mail.google.com/mail/?view=cm&fs=1&to=${encodeURIComponent(EMAIL)}&su=${encodeURIComponent('Hello, AdaptEd team')}`} target="_blank" rel="noopener noreferrer"><Mail size={18}/>{tr('Open Gmail','فتح Gmail')}<ArrowUpRight size={18}/></a><p>{tr('Opens Gmail in a new tab. Write and send your message there.','يفتح Gmail بتبويب جديد. اكتب رسالتك وأرسلها من هناك.')}</p></div></section>
  <section className="sp-faq" aria-labelledby="support-faq-title"><div><p className="sp-kicker">{tr('A LITTLE CLARITY','إجابات تساعدك')}</p><h2 id="support-faq-title">{tr('Before you say hello.','قبل ما تتواصل.')}<span>{tr('A few helpful answers.','كم جواب يفيدك.')}</span></h2></div><div className="sp-faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}<Plus size={18}/></summary><p>{a}</p></details>)}</div></section><div className="sp-closing"><span>{tr('One lesson. Every learner.','درس واحد. لكل متعلّم.')}</span><Link to={user?'/app':'/'}>{tr('Back to AdaptEd','العودة إلى AdaptEd')}<ArrowUpRight size={17}/></Link></div>
 </div></PublicShell>
}
