import {useEffect,useId,useState} from 'react'
import {Link} from 'react-router-dom'
import {ArrowUpRight,Check,Copy,Mail,Plus,Sparkles} from 'lucide-react'
import {useApp} from '../context/AppContext'
import PublicShell from '../components/PublicShell'

const EMAIL='adaptedteam.3@gmail.com'
const TEAM=[{name:'Lubna Mohammed Eyad',color:'sky',motif:'arch',hair:'waves'},{name:'Zahraa Qasim',color:'sage',motif:'orbit',hair:'bob'},{name:'Amani Khalid',color:'pink',motif:'fold',hair:'ponytail'}]
function TeamAvatar({hair}){
 const id=useId()
 return <svg className="sp-avatar" viewBox="0 0 160 180" fill="none" aria-hidden="true" focusable="false">
  <defs><linearGradient id={`${id}-top`} x1="45" y1="110" x2="115" y2="160" gradientUnits="userSpaceOnUse"><stop className="sp-avatar-light"/><stop offset="1" className="sp-avatar-deep"/></linearGradient><linearGradient id={`${id}-face`} x1="65" y1="50" x2="100" y2="102" gradientUnits="userSpaceOnUse"><stop stopColor="#fff0e3"/><stop offset="1" stopColor="#edc6b0"/></linearGradient></defs>
  <circle cx="80" cy="87" r="69" fill="#fff" fillOpacity=".27"/><circle cx="80" cy="87" r="68.5" stroke="#fff" strokeOpacity=".6"/>
  {hair==='waves'&&<path d="M43 72c-5-38 17-48 37-48 30 0 44 21 36 49-2 13 9 16 4 29-3 9 7 17-1 26-11 14-68 15-80-1-7-10 3-18 0-27-5-12 5-17 4-28Z" fill="#5e493f"/>}
  {hair==='bob'&&<path d="M43 66c0-28 16-42 37-42 26 0 38 17 38 43l5 37c-9 19-77 19-86 0l6-38Z" fill="#493e37"/>}
  {hair==='ponytail'&&<><path d="M108 44c24-17 37 4 28 25-10 21-1 31-8 43-19-3-26-26-18-43Z" fill="#67483c"/><path d="M44 70c-7-30 10-46 35-47 28-1 43 18 38 48l-10 24H52L44 70Z" fill="#67483c"/></>}
  <ellipse cx="80" cy="161" rx="44" ry="6" className="sp-avatar-shadow"/>
  <path d="M32 148c0-26 20-40 48-40s48 14 48 40v5c0 8-22 13-48 13s-48-5-48-13v-5Z" fill={`url(#${id}-top)`}/>
  <path d="M68 98v16c0 11 24 11 24 0V98" fill="#ecc4ac"/><path d="m62 112 18 13 18-13" stroke="#fff" strokeOpacity=".65" strokeWidth="4" strokeLinecap="round"/>
  <ellipse cx="50" cy="78" rx="6" ry="9" fill="#ecc4ac"/><ellipse cx="110" cy="78" rx="6" ry="9" fill="#ecc4ac"/>
  <path d="M51 61c0-23 58-24 58 0v21c0 20-14 33-29 33S51 102 51 82V61Z" fill={`url(#${id}-face)`}/>
  {hair==='waves'&&<><path d="M49 74c-10-28 6-42 31-42 22 0 37 14 31 37-18-2-25-18-26-24-6 16-20 22-36 29Z" fill="#5e493f"/><path d="M83 33c-17 1-28 10-29 24" stroke="#9a7861" strokeOpacity=".6" strokeWidth="3" strokeLinecap="round"/><path d="M106 73c7 28-1 35 3 55" stroke="#8c6955" strokeOpacity=".5" strokeWidth="4" strokeLinecap="round"/></>}
  {hair==='bob'&&<><path d="M49 66c-2-23 10-34 31-34 23 0 36 14 31 36-17 0-29-12-31-19-5 12-17 19-31 17Z" fill="#493e37"/><path d="M49 48c18-18 45-17 63 0" stroke="#b7d69d" strokeWidth="6" strokeLinecap="round"/><path d="M46 70v29m67-29v29" stroke="#493e37" strokeWidth="7" strokeLinecap="round"/></>}
  {hair==='ponytail'&&<><path d="M48 68c-4-25 10-38 31-38 23 0 36 14 34 38-19-7-31-17-36-25-5 14-15 21-29 25Z" fill="#67483c"/><path d="m115 43 13-13 5 18-16 2-9 11-7-15Z" fill="#e6a4bf"/><circle cx="117" cy="46" r="5" fill="#f5cddd"/></>}
  <path d="M62 77c3-3 6-3 9 0m18 0c3-3 6-3 9 0" stroke="#51413a" strokeWidth="2.2" strokeLinecap="round"/>
  <ellipse cx="60" cy="87" rx="6" ry="3" fill="#e9a89e" fillOpacity=".55"/><ellipse cx="100" cy="87" rx="6" ry="3" fill="#e9a89e" fillOpacity=".55"/>
  <path d="M73 93c4 5 10 5 14 0" stroke="#ba7b6b" strokeWidth="2" strokeLinecap="round"/>
  <path d="M42 140c6-12 14-17 22-18" stroke="#fff" strokeOpacity=".5" strokeWidth="3" strokeLinecap="round"/>
 </svg>
}
export default function Support(){
 const {tr,lang,user}=useApp(),[copyState,setCopyState]=useState('idle')
 useEffect(()=>{document.title=`${lang==='ar'?'الدعم والفريق':'Support & Team'} · AdaptEd`},[lang])
 useEffect(()=>{if(copyState==='idle')return;const timer=setTimeout(()=>setCopyState('idle'),4500);return()=>clearTimeout(timer)},[copyState])
 async function copyEmail(){try{await navigator.clipboard.writeText(EMAIL);setCopyState('copied')}catch{setCopyState('failed')}}
 const faqs=[
  [tr('Do I need an account to reach you?','هل أحتاج حسابًا حتى أتواصل؟'),tr('You do not need an AdaptEd account. Contact our team from your own email. Gmail may ask you to sign in to your Google account.','ما تحتاج حساب AdaptEd. تواصل معنا من إيميلك الشخصي. Gmail ممكن يطلب تسجيل دخول بحساب Google الخاص بك.')],
  [tr('What should I include in a problem report?','شنو أكتب إذا واجهتني مشكلة؟'),tr('Tell us which page you were on, the steps you tried, and what happened. Your browser or device and a screenshot can help.','اذكر الصفحة، والخطوات اللي جرّبتها، وشنو صار بعدها. اسم المتصفح أو الجهاز وصورة للمشكلة يساعدونا نفهمها.')],
  [tr('Can I use another email service?','أكدر أستخدم بريد غير Gmail؟'),tr('Of course. Copy our email address and paste it into the recipient field in your preferred email service. Write your message and send it there.','أكيد. انسخ عنواننا والصقه بخانة المستلم بخدمة البريد اللي تستخدمها. اكتب رسالتك وأرسلها من هناك.')]
 ]
 return <PublicShell className="support-shell"><div className="support-page" dir={lang==='en'?'ltr':'rtl'}>
  <section className="sp-hero" aria-labelledby="support-title"><div className="sp-intro"><p className="sp-kicker"><span/>{tr('SUPPORT & TEAM','الدعم والفريق')}</p><h1 id="support-title">{tr('Built with care.','صنعناه باهتمام.')}<br/><em>{tr('Here for you.','ونحن هنا لأجلك.')}</em></h1><p className="sp-lead">{tr('Behind every lesson is a learner. Behind AdaptEd is a team that cares about their journey.','وراء كل درس متعلّم. ووراء AdaptEd فريق يهتم برحلته، ويؤمن أن لكل شخص طريقته في التعلّم.')}</p><div className="sp-hero-actions"><a className="sp-button" href="#support-contact">{tr('Talk to our team','تواصل مع الفريق')}<ArrowUpRight size={18}/></a><a className="sp-text-link" href="#support-team">{tr('Meet the people','تعرّف علينا')}<span aria-hidden="true">↓</span></a></div><div className="sp-signature"><div aria-hidden="true">{TEAM.map(member=><span className={`sp-avatar-${member.color}`} key={member.name}><TeamAvatar hair={member.hair}/></span>)}</div><p>{tr('Three minds. One shared purpose.','ثلاثة عقول. هدف واحد.')}<small>{tr('Making room for every learner.','مساحة لكل متعلّم.')}</small></p></div></div>
   <div className="sp-art" aria-hidden="true"><div className="sp-art-grid"/><div className="sp-orbit"/><div className="sp-orbit sp-orbit-two"/><span className="sp-art-star">✳</span><span className="sp-art-caption">{tr('A HUMAN CONNECTION','تواصل إنساني')}</span><div className="sp-letter-back"/><div className="sp-letter"><span className="sp-letter-top"><b>AdaptEd</b><Mail size={24}/></span><p>{tr('A little help.','مساعدة صغيرة.')}<br/><em>{tr('A world of possibility.','وإمكانات كبيرة.')}</em></p><div className="sp-letter-rule"/><span className="sp-letter-sign">{tr('From our team, to you.','من فريقنا، إليك.')}</span><span className="sp-letter-stamp">AE<Sparkles size={13}/></span></div><div className="sp-art-note">{tr('Learning connects us.','التعلّم يجمعنا.')}</div><span className="sp-art-bottom">{tr('PEOPLE MAKE THE DIFFERENCE','الأثر يبدأ بالناس')}</span></div>
  </section>
  <section className="sp-team" id="support-team" aria-labelledby="team-title"><div className="sp-section-heading"><div><p className="sp-kicker">{tr('THE PEOPLE BEHIND ADAPTED','الفريق وراء ADAPTED')}</p><h2 id="team-title">{tr('Different minds.','أفكار مختلفة.')}<br/><span>{tr('One meaningful idea.','وفكرة تجمعنا.')}</span></h2></div><p>{tr('A shared belief brought us together: learning should make space for everyone. Meet the team bringing AdaptEd to life.','جمعنا إيمان واحد: التعلّم لازم يتّسع للجميع. هذا هو الفريق الذي حوّل فكرة AdaptEd إلى تجربة بين يديك.')}</p></div><div className="sp-team-grid">{TEAM.map(member=><article key={member.name} className={`sp-member sp-member-${member.motif} sp-avatar-${member.color}`}><div className="sp-member-art" aria-hidden="true"><div className="sp-member-lines"><i/><i/><i/></div><TeamAvatar hair={member.hair}/><span className="sp-member-mark"><Plus size={20}/></span></div><div className="sp-member-info"><p>{tr('ADAPTED TEAM','فريق ADAPTED')}</p><h3 dir="ltr">{member.name}</h3><span className="sp-member-line"/></div></article>)}</div><div className="sp-team-footnote"><span aria-hidden="true">✳</span><p>{tr('Built together. For the way you learn.','صنعناه معًا. لطريقتك في التعلّم.')}</p><b>AdaptEd</b></div></section>
  <section className="sp-contact" id="support-contact" aria-labelledby="contact-title"><div className="sp-contact-top"><div><p className="sp-kicker">{tr('ONE INBOX. THE WHOLE TEAM.','بريد واحد. للفريق كله.')}</p><h2 id="contact-title">{tr('Good conversations','كل حوار جميل')}<br/><em>{tr('start with hello.','يبدأ بمرحبًا.')}</em></h2></div><Mail size={76} strokeWidth={1} aria-hidden="true"/></div><p className="sp-contact-lead">{tr('A question, an idea, or something we can improve. We’d love to hear from you.','سؤال، اقتراح، أو شيء نقدر نحسّنه. يسعدنا نسمع منك.')}</p><div className="sp-email-row"><span className="sp-email" dir="ltr">{EMAIL}</span><button type="button" className="sp-copy" onClick={copyEmail}>{copyState==='copied'?<Check size={17}/>:<Copy size={17}/>}<span>{copyState==='copied'?tr('Copied','تم النسخ'):tr('Copy email','نسخ الإيميل')}</span></button></div><p className="sp-copy-status" role="status" aria-live="polite">{copyState==='copied'?tr('Email address copied to your clipboard.','تم نسخ عنوان البريد.'):copyState==='failed'?tr('Copy is unavailable here. Select the address above and copy it manually.','النسخ غير متاح هنا. حدّد عنوان البريد أعلاه وانسخه يدويًا.'):''}</p><div className="sp-gmail-action"><a className="sp-button sp-button-light" href={`https://mail.google.com/mail/?view=cm&fs=1&to=${encodeURIComponent(EMAIL)}&su=${encodeURIComponent('Hello, AdaptEd team')}`} target="_blank" rel="noopener noreferrer"><Mail size={18}/>{tr('Open Gmail','فتح Gmail')}<ArrowUpRight size={18}/></a><p>{tr('Opens Gmail in a new tab. Write and send your message there.','يفتح Gmail بتبويب جديد. اكتب رسالتك وأرسلها من هناك.')}</p></div></section>
  <section className="sp-faq" aria-labelledby="support-faq-title"><div><p className="sp-kicker">{tr('A LITTLE CLARITY','إجابات تساعدك')}</p><h2 id="support-faq-title">{tr('Before you say hello.','قبل ما تتواصل.')}<span>{tr('A few helpful answers.','كم جواب يفيدك.')}</span></h2></div><div className="sp-faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}<Plus size={18}/></summary><p>{a}</p></details>)}</div></section><div className="sp-closing"><span>{tr('One lesson. Every learner.','درس واحد. لكل متعلّم.')}</span><Link to={user?'/app':'/'}>{tr('Back to AdaptEd','العودة إلى AdaptEd')}<ArrowUpRight size={17}/></Link></div>
 </div></PublicShell>
}
