import {Link} from 'react-router-dom'
import {Users,GraduationCap,Presentation,BookOpen,Sparkles,ArrowUpRight,RefreshCw,ShieldCheck,FileText,Video} from 'lucide-react'
import {useApp} from '../../context/AppContext'
import {useAdminResource} from '../../hooks/useAdminResource'
import {AdminHeading,AdminError,AdminLoading,AdminEmpty,AdminDate} from '../../components/admin/AdminUI'

export default function AdminDashboard(){
 const {tr,lang}=useApp(),stats=useAdminResource('stats'),lessons=useAdminResource('lessons')
 const format=value=>new Intl.NumberFormat(lang==='ar'?'ar-IQ':'en-GB').format(value)
 const metrics=[['totalUsers',Users,tr('Total users','إجمالي المستخدمين'),tr('Across the platform','على مستوى المنصة'),'all'],['totalStudents',GraduationCap,tr('Students','الطلاب'),tr('Learning at their own pace','يتعلّمون على راحتهم'),'students'],['totalTeachers',Presentation,tr('Teachers','المعلمون'),tr('Making learning possible','يصنعون فرص التعلّم'),'teachers'],['totalLessons',BookOpen,tr('Total lessons','إجمالي الدروس'),tr('Knowledge, ready to explore','معرفة جاهزة للاستكشاف'),'lessons'],['totalAIGenerations',Sparkles,tr('AI generations','توليدات الذكاء الاصطناعي'),tr('Generated learning content','محتوى تعليمي مولّد'),'ai']]
 const data=stats.data,total=data?.totalUsers||0
 const students=total?Math.min(100,data.totalStudents/total*100):0,teachers=total?Math.min(100-students,data.totalTeachers/total*100):0
 const segments=data?[[tr('Students','الطلاب'),data.totalStudents,'students'],[tr('Teachers','المعلمون'),data.totalTeachers,'teachers'],[tr('Other accounts','الحسابات الأخرى'),Math.max(0,total-data.totalStudents-data.totalTeachers),'other']]:[]
 const refresh=()=>{stats.reload();lessons.reload()}
 return <>
  <AdminHeading eyebrow={tr('THE BIG PICTURE','الصورة الكاملة')} title={tr('Your platform, at a glance.','منصتك، بنظرة واحدة.')} description={tr('A clear view of the people, lessons and learning you make possible.','نظرة واضحة على المستخدمين والدروس وفرص التعلّم في منصتك.')}><button className="ad-button" onClick={refresh} disabled={stats.pending||lessons.pending}><RefreshCw size={16} className={stats.pending?'spin':''}/>{tr('Refresh','تحديث')}</button></AdminHeading>
  <section className="ad-overview-hero"><div><p className="ad-eyebrow"><span/>{tr('ADAPTED ADMINISTRATION','إدارة ADAPTED')}</p><h2>{tr('Behind every lesson,','وراء كل درس،')}<br/><em>{tr('a world of possibility.','عالم من الإمكانات.')}</em></h2><p>{tr('Keep your community in view. Find the people and content that bring learning to life.','تابع مجتمع منصتك، وتعرّف على المستخدمين والمحتوى الذي يمنح التعلّم حياة.')}</p><Link to="/admin/users">{tr('Explore your community','استكشف مجتمعك')}<ArrowUpRight size={17}/></Link></div><div className="ad-hero-art" aria-hidden="true"><div className="ad-hero-ring"/><div className="ad-art-card ad-art-card-back"/><div className="ad-art-card"><span className="ad-art-seal"><ShieldCheck size={30}/></span><b>AdaptEd</b><span>{tr('One connected community','مجتمع تعلّم واحد')}</span><div className="ad-art-people"><GraduationCap/><Presentation/><BookOpen/></div></div><span className="ad-art-star">✳</span></div></section>
  <section aria-label={tr('Platform statistics','إحصائيات المنصة')} className="ad-stat-section">{stats.pending?<AdminLoading cards/>:stats.error?<AdminError error={stats.error} onRetry={stats.reload}/>:<><div className="ad-metrics">{metrics.map(([key,Icon,label,caption,tone])=><article className={`ad-metric ad-metric-${tone}`} key={key}><div><span>{label}</span><i><Icon size={20}/></i></div><strong>{format(data[key])}</strong><p>{caption}</p></article>)}</div><p className="ad-updated" role="status">{tr('Last refreshed','آخر تحديث')} · {new Intl.DateTimeFormat(lang==='ar'?'ar-IQ':'en-GB',{hour:'2-digit',minute:'2-digit'}).format(stats.updatedAt)}</p></>}</section>
  <div className="ad-dashboard-grid"><section className="ad-panel"><div className="ad-panel-heading"><div><p className="ad-eyebrow">{tr('YOUR COMMUNITY','مجتمع المنصة')}</p><h2>{tr('People make the difference.','الأثر يبدأ بالناس.')}</h2></div><Users size={22}/></div>{stats.pending?<div className="ad-skeleton ad-chart-skeleton"/>:stats.error?<p className="ad-panel-note">{tr('Refresh the statistics to view your community breakdown.','أعد تحميل الإحصائيات لعرض توزيع المستخدمين.')}</p>:<div className="ad-community"><div className="ad-donut" role="img" aria-label={segments.map(([label,count])=>`${label}: ${format(count)}`).join(', ')} style={{background:total?`conic-gradient(#39583f 0% ${students}%,#a6bf74 ${students}% ${students+teachers}%,#e7d6ad ${students+teachers}% 100%)`:'#e9ecdf'}}><div><strong>{format(total)}</strong><span>{tr('Total users','إجمالي المستخدمين')}</span></div></div><ul className="ad-legend">{segments.map(([label,count,tone])=><li key={tone}><span><i className={`ad-dot-${tone}`}/>{label}</span><strong>{format(count)}</strong></li>)}</ul></div>}</section><section className="ad-panel ad-directory"><div className="ad-panel-heading"><div><p className="ad-eyebrow">{tr('YOUR WORKSPACE','مساحة عملك')}</p><h2>{tr('Everything in its place.','كل شيء في مكانه.')}</h2></div></div><Link to="/admin/users"><span className="ad-directory-icon"><Users size={23}/></span><div><h3>{tr('User directory','دليل المستخدمين')}</h3><p>{tr('Find an account by name, email or role.','ابحث عن حساب بالاسم أو الإيميل أو الدور.')}</p></div><ArrowUpRight size={20}/></Link><Link to="/admin/lessons"><span className="ad-directory-icon"><BookOpen size={23}/></span><div><h3>{tr('Lesson directory','دليل الدروس')}</h3><p>{tr('Browse lesson titles, owners and file types.','تصفّح عناوين الدروس وأصحابها وأنواع ملفاتها.')}</p></div><ArrowUpRight size={20}/></Link></section></div>
  <section className="ad-panel ad-recent"><div className="ad-panel-heading"><div><p className="ad-eyebrow">{tr('LATEST ADDITIONS','أحدث الإضافات')}</p><h2>{tr('Recently added lessons','الدروس المضافة حديثًا')}</h2></div><Link className="ad-text-link" to="/admin/lessons">{tr('View all lessons','كل الدروس')}<ArrowUpRight size={16}/></Link></div>{lessons.pending?<AdminLoading/>:lessons.error?<AdminError error={lessons.error} onRetry={lessons.reload}/>:!lessons.data.length?<AdminEmpty/>:<div className="ad-recent-list">{lessons.data.slice(0,5).map(lesson=><div className="ad-recent-row" key={lesson.id}><span className={`ad-file-icon ${lesson.file_type==='Video'?'is-video':''}`}>{lesson.file_type==='Video'?<Video size={19}/>:<FileText size={19}/>}</span><div><strong dir="auto">{lesson.title||lesson.original_name||tr('Untitled lesson','درس بدون عنوان')}</strong><small dir="auto">{lesson.owner_name||'—'}</small></div><span className="ad-file-type">{lesson.file_type||'—'}</span><AdminDate value={lesson.created_at}/></div>)}</div>}</section>
 </>
}
