import {useState} from 'react'
import {BookOpen,RefreshCw,SlidersHorizontal,FileText,Video,File} from 'lucide-react'
import {useApp} from '../../context/AppContext'
import {useAdminResource} from '../../hooks/useAdminResource'
import {AdminHeading,AdminSearch,AdminLoading,AdminError,AdminEmpty,AdminPagination,AdminDate} from '../../components/admin/AdminUI'

const PAGE_SIZE=12
export default function AdminLessons(){
 const {tr,lang}=useApp(),[search,setSearch]=useState(''),[type,setType]=useState(''),[page,setPage]=useState(1)
 const resource=useAdminResource('lessons',search),rows=(resource.data||[]).filter(lesson=>!type||lesson.file_type===type),current=Math.min(page,Math.max(1,Math.ceil(rows.length/PAGE_SIZE)))
 const updateSearch=value=>{setSearch(value);setPage(1)},clear=()=>{setSearch('');setType('');setPage(1)}
 const format=value=>new Intl.NumberFormat(lang==='ar'?'ar-IQ':'en-GB').format(value)
 return <>
  <AdminHeading eyebrow={tr('KNOWLEDGE ACROSS YOUR PLATFORM','المعرفة في منصتك')} title={tr('A home for every lesson.','مكان لكل درس.')} description={tr('Explore the learning materials your community has brought to AdaptEd.','استكشف المواد التعليمية التي أضافها مجتمعك إلى AdaptEd.')}><span className="ad-heading-symbol"><BookOpen size={27}/></span></AdminHeading>
  <section className="ad-panel ad-list-panel"><div className="ad-panel-heading"><div><h2>{tr('Lesson directory','دليل الدروس')}</h2><p>{tr('Lesson titles, owners and upload dates at a glance.','عناوين الدروس وأصحابها وتواريخ رفعها بنظرة واحدة.')}</p></div><button className="ad-icon-button" onClick={resource.reload} disabled={resource.pending} aria-label={tr('Refresh lessons','تحديث الدروس')}><RefreshCw size={18} className={resource.pending?'spin':''}/></button></div>
   <div className="ad-filters"><AdminSearch value={search} onChange={updateSearch} label={tr('Search lessons or owners','ابحث عن درس أو صاحبه')}/><label className="ad-select"><SlidersHorizontal size={16}/><span className="sr-only">{tr('Filter by file type','تصفية حسب نوع الملف')}</span><select value={type} onChange={event=>{setType(event.target.value);setPage(1)}}><option value="">{tr('All file types','كل أنواع الملفات')}</option><option value="PDF">PDF</option><option value="Video">{tr('Video','فيديو')}</option><option value="Other">{tr('Other','أخرى')}</option></select></label></div>
   <div className="ad-results-info" role="status" aria-live="polite"><span>{resource.pending?tr('Finding lessons…','جارٍ تحميل الدروس…'):resource.error?tr('Results unavailable','النتائج غير متاحة'):`${format(rows.length)} ${tr('lessons','دروس')}`}</span>{(search||type)&&<button onClick={clear}>{tr('Clear filters','مسح الفلاتر')}</button>}</div>
   {resource.pending?<AdminLoading/>:resource.error?<AdminError error={resource.error} onRetry={resource.reload}/>:!rows.length?<AdminEmpty filtered={Boolean(search||type)} onClear={clear}/>:<><div className="ad-table-scroll" tabIndex={0} role="region" aria-label={tr('Lesson directory table','جدول الدروس')}><table className="ad-table ad-lessons-table"><caption className="sr-only">{tr('Lessons, their owners, file types and upload dates','الدروس وأصحابها وأنواع الملفات وتواريخ الرفع')}</caption><thead><tr><th scope="col">{tr('Title','العنوان')}</th><th scope="col">{tr('Owner','صاحب الدرس')}</th><th scope="col">{tr('Type','النوع')}</th><th scope="col">{tr('Date','التاريخ')}</th></tr></thead><tbody>{rows.slice((current-1)*PAGE_SIZE,current*PAGE_SIZE).map(lesson=><tr key={lesson.id}><td><div className="ad-lesson-cell"><span className={`ad-file-icon ${lesson.file_type==='Video'?'is-video':''}`}>{lesson.file_type==='Video'?<Video size={19}/>:lesson.file_type==='PDF'?<FileText size={19}/>:<File size={19}/>}</span><div><strong dir="auto">{lesson.title||lesson.original_name||tr('Untitled lesson','درس بدون عنوان')}</strong>{lesson.original_name&&<small dir="auto">{lesson.original_name}</small>}</div></div></td><td><div className="ad-owner"><strong dir="auto">{lesson.owner_name||'—'}</strong><small dir="ltr">{lesson.owner_email||'—'}</small></div></td><td><span className={`ad-type-pill ${lesson.file_type==='Video'?'is-video':''}`}>{lesson.file_type==='Video'?tr('Video','فيديو'):lesson.file_type==='Other'?tr('Other','أخرى'):lesson.file_type||'—'}</span></td><td><AdminDate value={lesson.created_at}/></td></tr>)}</tbody></table></div><AdminPagination page={current} total={rows.length} pageSize={PAGE_SIZE} onChange={setPage}/></>}
  </section>
 </>
}
